//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_Main : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean Shoot
        {
            get
            {
                return SteamVR_Actions.main_Shoot;
            }
        }
        
        public virtual SteamVR_Action_Pose Pose
        {
            get
            {
                return SteamVR_Actions.main_Pose;
            }
        }
        
        public virtual SteamVR_Action_Boolean SlowTime
        {
            get
            {
                return SteamVR_Actions.main_SlowTime;
            }
        }
        
        public virtual SteamVR_Action_Boolean Xray
        {
            get
            {
                return SteamVR_Actions.main_Xray;
            }
        }
    }
}
